# https://docs.digitalocean.com/glossary/app-spec
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/
# The app spec, is a YAML manifest that declaratively states everything about your app.
# Including each resource and all of your app’s environment variables and configuration variables.
name: 'roblox-plus'

# The domain names where the app is accessible on the public internet.
domains:
  - domain: 'roblox.plus'
    type: 'PRIMARY'

# The region to deploy the app into.
# See also: https://docs.digitalocean.com/products/platform/availability-matrix/#app-platform-availability
region: sfo

# Get alerts when things go horribly wrong.
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

services:
  # This is the backend for the push notifications demo,
  # the thing actually sending the push notifications.
  - name: 'api'
    github:
      branch: 'master'
      deploy_on_push: true
      repo: 'roblox-plus/extension'
    health_check:
      http_path: '/application-metadata'
    http_port: 80
    instance_count: 1
    instance_size_slug: 'basic-xxs'
    envs:
      - key: 'ROBLOX__AUTHENTICATION__CLIENTID'
        scope: 'RUN_TIME'
        value: '2147861207470534820'

      # This should be safe to commit to source control, it's encrypted?
      # https://www.digitalocean.com/community/questions/what-are-app-spec-best-practices-for-keeping-env-secrets-secret?comment=193546
      - key: 'AUTHENTICATION_KEYS_JSON'
        scope: 'RUN_TIME'
        type: 'SECRET'
        value: |
          EV[1:f86FR1X/vf5cm+17HwT7gWbL8bhV2MaA:xpUQo/Wmzzav0/FQapgmdYVChwJmIqSb9b38GkzoZTu8mhP5ijJbVUgPwRPubFpyPq9iWyqum0snlGCSO91g+Z2RoHjEaOFt5JPMJ+GgK7+dH1Ec6BxFgtDUaTjlYcsb/D5tNn5MWobcvj0e/mlj6/FM1aZmyna6ldwHjLFTZQu3Goqulm3djzKgmzR5n0uM/q3/ZAN8FaEFh0v0ytPG2mzAIWUrU6NVaFEhGXdUMhZGiSTHkXcvifX33cF9cPTJHSZ07Y+xeC+/JCfOTCGNXuQY8YDbUTj0Zx1v+Xe32oe9yfoAi9ULuIS7y++nh163wL+ejCVNh5wA3tx3h7XzIypxKLd2qCdEY9PgfgVBLxZCDOCzOAQVqVdEMJCfngjlI6BKUofdOfhNJ9doEvkb1iOWRwnnrKMiJT7Np6rEjgM6D4qhGqPU5jSbDAw//DV1+xmthQQj/Ap3+86lRPeJJPVCAXVgPzFCSy1tT7vjXDa8kla7wRW3AuvRdiwiXkFfdx/aTTNjBCQcO0OrZ36jIXimiLRwvp0Wc9IjTykx9SnW1YCFSadj+Bh47iGhDEARA7DJFoz5A42wtD+ghmEjxaLias8otKzGX+Q+Agk0RtHxUf3SDe1xpxVTXPEp2ud5CVoGz0WehUncVnsmF5+GKLUMcyITwLaMAiAeeSGIclY2942vPX68ZH7QY7rdXGA12WkEuvNAWLC/iG8sy0+9YI17b/9unyPMv0n2HxPUUAjqIPsbSQCuYeoqkESCNSqv1xzy6nZpq5uxJYaqgthlb0BLBvE5PoZjMu5O9SPE7jWFiSrVkeIl2gi4z8V8G3e4Ud2wBIy5X1b+VE4HTd99++B2FsumGmy5sLvm7zXMrvcFyqEyIKg9TktULWO7WTWwsgSxXGSo+elJCZ8M39OczZkv73JBuvH0SU2SEIE6zwfmiSbgNBjvTqpMrXJyFQ9S5QrLjfxpA76aD2xot1PrtFebIhRyNglufOPUbGgtAiQzXdSQj0/9L90rgfKjmmSYeTvENswNNQbfbucnUYp3hW0SZunB2kxs2ZqQ7dQaDVVRoyrsO0REfcEfKBPm4FLG6DMHm8yEc3gHmTCYFeR0sHk4C/3vXvMgjhatPAk7uGfBDk0FBOi9sH6qnnBH/6qm4iCRQ+NGEJ1w40xnBkOW0N6sLUNcKPiSiShBJvP2OTLFML6G489X/wIxlrQk6jEJGnWneadUTgaWANnBY6lMJM0d6CpjBDJbkuQMeT/DwQAMtNiTjz9Km7lBwiE3Gq+cjnSJ0BLhHRW1dWulcZ2+KOsmsKai6efjvJfT9/cNAjXw1d/gSEBQyh7q13e1+wgOCpyPdOC+spVLL1LupzI5qkGTKVox7w0gTDYsyAtBpDon5ct3rdTxTfNtGkhioTCQaA4Q/DnQiO7X4C5kNS3zmz4Nop1KKBGS24k9lxwM4tJStwEaTBhEN865VfFuaPFRIZ3NnrT3vheJ5MLf+ugzGtctmhLPJGctc5Dj+3VlGA/cvfYirUxttb4jR4/jxoYfMerJ4chlq5tyqEtRL2S9HQpBS3gRE6st9r0HrpQQatsvwBc9JQ1tCgeNF5bgthvFCJBq9yV/LfpQRgU0HsY8otJY9xC5lYvtXb0XM6S3kMsY5yNW7XnwQUYdoB7jWUE=]

      - key: 'ROBLOX__AUTHENTICATION__CLIENTSECRET'
        scope: 'RUN_TIME'
        type: 'SECRET'
        value: |
          EV[1:LZ/by9DvU7HPk7+yrPgyafjmY+t0fRiG:u98Py25ywo9MJGq0Pb6on6+rJD34ivb0bsl7MxHqSN9Z+SpiCDh4slrDpJITw6Ks3TxMIsBwUy1y6xUc/BwjChiqrqyfS5ZiPbn/NGIlU1Q0wqQU]
    routes:
      - path: /api
        preserve_path_prefix: true
    cors:
      allow_methods:
        - GET
      allow_origins:
        - exact: http://localhost:3000
        - exact: https://localhost:3000
    source_dir: 'services/web-api'
    dockerfile_path: 'services/web-api/Dockerfile'

static_sites:
  # This is the app that the humans interact with in their web browsers.
  - name: 'app'
    github:
      branch: 'master'
      deploy_on_push: true
      repo: 'roblox-plus/extension'
    source_dir: 'services/web-app'
    output_dir: '/app/build'
    dockerfile_path: 'services/web-app/Dockerfile'
    routes:
      - path: /
    catchall_document: index.html
