# https://docs.digitalocean.com/glossary/app-spec
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/
# The app spec, is a YAML manifest that declaratively states everything about your app.
# Including each resource and all of your app’s environment variables and configuration variables.
name: 'roblox-plus'

# The domain names where the app is accessible on the public internet.
domains:
  - domain: 'roblox.plus'
    type: 'PRIMARY'

# The region to deploy the app into.
# See also: https://docs.digitalocean.com/products/platform/availability-matrix/#app-platform-availability
region: sfo

# Get alerts when things go horribly wrong.
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

services:
  # This is the backend for the push notifications demo,
  # the thing actually sending the push notifications.
  - name: 'api'
    github:
      branch: 'master'
      deploy_on_push: true
      repo: 'roblox-plus/extension'
    health_check:
      http_path: '/application-metadata'
    http_port: 80
    instance_count: 1
    instance_size_slug: 'basic-xxs'
    envs:
      # This should be safe to commit to source control, it's encrypted?
      # https://www.digitalocean.com/community/questions/what-are-app-spec-best-practices-for-keeping-env-secrets-secret?comment=193546
      - key: 'AUTHENTICATION_KEYS_JSON'
        scope: 'RUN_TIME'
        type: 'SECRET'
        value: |
          EV[1:rdg/MVMQsHfFy2xrNFDZXgGFwonJOlX6:2Yw3s9npC+4ROhcdIVEETdT0BLF75J7eWXqxmlMO7a5NmVQEOUT+ITOw0Ke4c9Ww9mrSSytVyu1C4zg8Dkb427qx4ZJsgIy4M+A6GDkjXZhH8eyKGSabY/j1mqEfTXe6Z0gzbkinEzVHu/4ptoPuTEiElupEiMarauC+jYpKqaWksmTi7hVJM54DMD/q3rNVEVTbVL5fy/fhx56pw5wPtuIxD9SXGWLEkxOmCNneiRz2qbkSYvVEixz77JsNQ2vtJz1MCn4I5fQnl1wEYbasIu9TmyIdVvoPC8ViusmQ/ENOwanY3U3ihedzA/q09mwp7W5i7bppZWGLnvkyisp26ls1bC3m5zRmMyCF7MDq2zEz8xyKNe7QQdt3zH5ohC+fvUBuDIxsDnA/uaNj/ZI/LTYUZlIqS0LRKoy/WsbRb1femPLOTEgu/ggb+QtmaMxgUej6U4y1w6G2AhQh6MwMQcaArnpz8G3p7tAE0epR/DiStnD+3NbFZZMgYAPNGJjSlx/Ek8UfGWHei+0eno5wnEo4OE9zB1ESCIcawJrTDIdaChBVvs3G5BNFk96+9Nw2OFZSoG99pETX+4+OOG0X69ABFNF5koIxQtV1H4Upfd19mFEIzwKQI8SmJgga5S7/udcpyphkUaD4k72/NXlDtgaPLofiba1WvXhY+rj/klZqB9T6t3ZiaNCGqbqn8wL/P80Po3u2RtYYuN474gvXrEbFbnkMXVq1iL4AbXftxnLAfvNSznHvXKAeOU9bDu7zK+ilY/drXtCBYCLTHDCSr/nk75As9LmuM8uBsBha8xGKGc/Tzqc6QodzXp0IBMnN1DNtiGnPpb2ckxMTDCZfKgE5YtuDArgMGitRouMN68ClpYNX+nGQlpfAEVORcr1by/gTm6JwMPxeLJTJTtAXLAc5f1PcGe8COwDxgf1n2zjNY5mXVFBbv99+BGZ6nbWvh4G6VH5g6RGsIGsvRaflwtpEwLMvmPYD+LKXAWyl0dLpDnzwVBhCcZJd20CmOZ3SymkACDLypfRgsxFesNO8CknIunqXFlMs095/Fy9zmc5wulpUL6YN0opYmT1zwOKYKAf0CDpp3+8FNeCYUMNiXh0TJrNfnx85meOU2xKafCUcKR9L7yUVm4CHqRUB+5kvgCn2ZVxiZRhlUcmeHXT5gboCYhA8RpJe1XRbpovFL0tmUYygPNyDycHLFm2t3CP0oHu3lZBJ31N5B8Y2ulwBH1hBJnCMgGqIkALDFZN0Bw3NqYa9sDqb2lW8SBxCFfH8sTgYlP/GvSybrg6AIXElw0stce3jlLTkjCr175iI/FiiZWT0OtANXtq/GMj0ZUODUhmvATu4WOqx20cOqyEOmPqnBLiWosrFo/2saTPGoSbJrLlRejIYmC3bBURTV6p4bEp8RUzMtJEGAbXpSYV++RvTE5L68joHQaGtkFwHHr5JnTZ5B/ddNif1eAmAaIxaaUl3iRU1CbMEZRBQpoAXI0DIlOwUu9mkM/s2plv6h5rtHK7eJq4A0jtshFr62WDNEhFGXpMzvJ/rCnfc8dfPVvIAoXmoVB0lnVgBm3t8UElPPsGQyjUeSx6UBxq65yfQGh9CwIBkPOuyHBd1T6aqWU0Htbc0CZenMmgO2bI/91yhEKIXjzblmg/7VM0ZmM8=]
    routes:
      - path: /api
        preserve_path_prefix: true
    cors:
      allow_methods:
        - GET
      allow_origins:
        - exact: http://localhost:3000
        - exact: https://localhost:3000
    source_dir: 'services/web-api'
    dockerfile_path: 'services/web-api/Dockerfile'

static_sites:
  # This is the app that the humans interact with in their web browsers.
  - name: 'app'
    github:
      branch: 'master'
      deploy_on_push: true
      repo: 'roblox-plus/extension'
    source_dir: 'services/web-app'
    output_dir: '/app/build'
    dockerfile_path: 'services/web-app/Dockerfile'
    routes:
      - path: /
    catchall_document: index.html
