name: Package Extension

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: '📥 Clone Repository'
        uses: actions/checkout@v3

      - name: '🟩 Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      # Extension Versioning
      - name: Set manifest version
        run: |
          jq '.+= { "version": "3.${{ github.run_number }}.0" }' manifest.json > tmp.$$.json && mv tmp.$$.json manifest.json
          cat manifest.json
        working-directory: src

      # Build local modules
      - name: '🚚 npm install (libs/roblox)'
        run: npm ci
        working-directory: ./libs/roblox

      - name: '🏗️ Build libs/roblox'
        run: npm run build
        working-directory: ./libs/roblox

      - name: '🚚 npm install (libs/extension-utils)'
        run: npm ci
        working-directory: ./libs/extension-utils

      - name: '🏗️ Build libs/extension-utils'
        run: npm run build
        working-directory: ./libs/extension-utils

      - name: '🚚 npm install (libs/extension-messaging)'
        run: npm ci
        working-directory: ./libs/extension-messaging

      - name: '🏗️ Build libs/extension-messaging'
        run: npm run build
        working-directory: ./libs/extension-messaging

      # Build extension itself
      - name: '🚚 npm install'
        run: npm ci

      - name: '🏗️ Build'
        run: |
          npm run build

      # Attach build artifacts
      - name: Attach build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: src/**
